In [2]:
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
df = pd.read_excel(r"C:\Users\Nada\Downloads\Customer Call List (1).xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [4]:
df= df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [5]:
df = df.drop(columns = "Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [6]:
# remove unwanted characters (1,2,3,.,_,/) from the beginning and end of Last_Name
df["Last_Name"] = df["Last_Name"].str.strip("123._/")

In [7]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [9]:
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','')
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [11]:
# split Address column into Street_Address, State, and Zip_Code using comma as delimiter
df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',',n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,93 West Main Street,NaN,NaN
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

In [12]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('Yes','Y')
df["Do_Not_Contact"] = df["Do_Not_Contact"].str.replace('No','N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,123 Shire Lane,Shire,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,93 West Main Street,NaN,NaN
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,768 City Parkway,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,N,1209 South Street,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,25th Main Street,New York,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,N,612 Shire Lane,Shire,NaN
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,343 City Parkway,NaN,NaN
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,121 Paper Avenue,Pennsylvania,NaN
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Y,N/a,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,NaN

In [ ]:
# replace all missing (NaN) values in the DataFrame with empty strings
df = df.fillna('')
df = df.replace('N/a','')

In [15]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,No,N,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,

In [ ]:
# remove rows where Do_Not_Contact is 'Y'
for x in df.index:
    if df.loc[x, "Do_Not_Contact"] == 'Y':
        df.drop(x, inplace=True)

df
#df = df[df["Do_Not_Contact"] != 'Y']

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,123 Shire Lane,Shire,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,,
6,1007,Jeff,Winger,,1209 South Street,No,N,1209 South Street,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Yes,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,

In [17]:
for x in df.index:
    if df.loc[x, "Phone_Number"] == '':
        df.drop(x, inplace=True)

df

#Another way to drop null values
#df = df.dropna(subset="Phone_Number"), inplace=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,123 Shire Lane,Shire,
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,,
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,25th Main Street,New York,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,,
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,

In [18]:
# reset index after deleting rows and drop old index
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_Code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,,
5,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,

In [28]:
dh = pd.read_excel(r"C:\Users\Nada\Downloads\Book1.xlsx")

In [29]:
dh

,Player,Span,Mat,Inns,NO,Runs,HS,Ave,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24
58,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0
59,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+
60,Hashmatullah Shahidi (AFG),2018-2025,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0

In [64]:
dh = dh.rename(columns = {'Mat': 'Matches', 'NO': 'Not_Outs', 'HS': 'Highest_Inns_Score', 'BF':'Balls_Faced', 'SR':'Batting_Strike_Rate'})

In [36]:
dh.isnull().any()

Player                 False
Span                   False
Matches                False
Inns                   False
Not_Outs               False
Runs                   False
HS                     False
Ave                    False
Balls_Faced            False
Batting_Strike_Rate    False
100                    False
50                     False
0                      False
4s                     False
6s                     False
dtype: bool

In [38]:
# filter DataFrame to show only rows where Player is CL Walcott (WI)
dh[dh['Player']=='CL Walcott (WI)']

,Player,Span,Matches,Inns,Not_Outs,Runs,HS,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
13,CL Walcott (WI),1948-1960,44,74,7,3798,220,56.68,-,-,15,14,1,107+,11

In [39]:
dh.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
57    False
58    False
59    False
60    False
61    False
Length: 62, dtype: bool

In [41]:
# filter rows where Player is in a list of selected players
dh[dh['Player'].isin(['GA Headley (WI)', 'GS Sobers (WI)', 'JB Hobbs (ENG)', 'V Kohli (IND)'])]

,Player,Span,Matches,Inns,Not_Outs,Runs,HS,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1
10,GS Sobers (WI),1954-1974,93,160,21,8032,365*,57.78,4063+,53.58,26,30,12,593+,32+
12,JB Hobbs (ENG),1908-1930,61,102,7,5410,211,56.94,5363+,46.22,15,28,4,276+,8

In [45]:
dh['Span'].str.split(pat = '-')

0     [1928, 1948]
1     [2022, 2025]
2     [2015, 2016]
3     [1963, 1970]
4     [1930, 1954]
          ...
57    [2002, 2014]
58    [1924, 1934]
59    [1930, 1938]
60    [2018, 2025]
61    [1928, 1934]
Name: Span, Length: 62, dtype: object

In [47]:
dh['Span'].str.split(pat = '-').str[1]

0     1948
1     2025
2     2016
3     1970
4     1954
      ...
57    2014
58    1934
59    1938
60    2025
61    1934
Name: Span, Length: 62, dtype: object

In [49]:
dh['Rookie_Year'] = dh['Span'].str.split(pat = '-').str[0]

In [53]:
dh['Final_Year'] = dh['Span'].str.split(pat = '-').str[1]

In [54]:
dh

,Player,Span,Matches,Inns,Not_Outs,Runs,HS,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),2022-2025,14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025
2,AC Voges (AUS),2015-2016,20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),1963-1970,23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),1930-1954,22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014
58,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934
59,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938
60,Hashmatullah Shahidi (AFG),2018-2025,11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2018,2025
61,DR Jardine (ENG),1928-1934,22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934

In [55]:
#Here we remove the ‘Span’ column from the DataFrame df using the drop method with axis=1, which specifies that a column (not a row) is being dropped.
dh = dh.drop(['Span'], axis = 1)

In [56]:
dh.head()

,Player,Matches,Inns,Not_Outs,Runs,HS,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954

In [57]:
dh['Player'].str.split(pat = '(')

0               [DG Bradman , AUS)]
1               [PHKD Mendis , SL)]
2                 [AC Voges , AUS)]
3                [RG Pollock , SA)]
4                [GA Headley , WI)]
                  ...
57             [GC Smith , ICC/SA)]
58             [WH Ponsford , AUS)]
59               [SJ McCabe , AUS)]
60    [Hashmatullah Shahidi , AFG)]
61              [DR Jardine , ENG)]
Name: Player, Length: 62, dtype: object

In [58]:
dh['Country'] = dh['Player'].str.split(pat = '(').str[1]

In [59]:
dh

,Player,Matches,Inns,Not_Outs,Runs,HS,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country
0,DG Bradman (AUS),52,80,10,6996,334,99.94,9800+,58.6,29,13,7,626+,6,1928,1948,AUS)
1,PHKD Mendis (SL),14,24,3,1316,182*,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL)
2,AC Voges (AUS),20,31,7,1485,269*,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS)
3,RG Pollock (SA),23,41,4,2256,274,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA)
4,GA Headley (WI),22,40,4,2190,270*,60.83,416+,56,10,5,2,104+,1,1930,1954,WI)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,GC Smith (ICC/SA),117,205,13,9265,277,48.25,15525,59.67,27,38,11,1165,24,2002,2014,ICC/SA)
58,WH Ponsford (AUS),29,48,4,2122,266,48.22,3118+,44.77,7,6,1,119+,0,1924,1934,AUS)
59,SJ McCabe (AUS),39,62,5,2748,232,48.21,3217+,60.02,6,13,4,241+,5+,1930,1938,AUS)
60,Hashmatullah Shahidi (AFG),11,21,5,771,246,48.18,1629,47.32,2,2,0,87,1,2018,2025,AFG)
61,DR Jardine (ENG),22,33,6,1296,127,48.00,2110+,25.59,1,10,2,53+,0,1928,1934,ENG)

In [61]:
dh['Country'] = dh['Country'].str.split(pat = ')').str[0]

In [63]:
dh['Player'] = dh['Player'].str.split(pat = '(').str[0]

In [65]:
dh['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     NaN
1     182
2     269
3     NaN
4     270
     ...
57    NaN
58    NaN
59    NaN
60    NaN
61    NaN
Name: Highest_Inns_Score, Length: 62, dtype: object

In [67]:
dh = dh.dropna(subset=['Highest_Inns_Score'])

In [68]:
dh['Highest_Inns_Score'].str.split(pat = '*').str[0]

0     NaN
1     182
2     269
3     NaN
4     270
     ...
57    NaN
58    NaN
59    NaN
60    NaN
61    NaN
Name: Highest_Inns_Score, Length: 62, dtype: object

In [70]:
dh['Highest_Inns_Score'] = dh['Highest_Inns_Score'].str.split(pat = '*').str[0]

In [72]:
dh['Highest_Inns_Score'] = dh['Highest_Inns_Score'].astype('Int64')

In [73]:
dh = dh.astype({'Rookie_Year':'int', 'Final_Year':'int'})

In [74]:
dh.dtypes

Player                  object
Matches                  int64
Inns                     int64
Not_Outs                 int64
Runs                     int64
Highest_Inns_Score       Int64
Ave                    float64
Balls_Faced             object
Batting_Strike_Rate     object
100                      int64
50                       int64
0                        int64
4s                      object
6s                      object
Rookie_Year              int64
Final_Year               int64
Country                 object
dtype: object

In [76]:
dh['Matches'] = dh['Matches'].astype(str).str.split(pat = '*').str[0]

In [77]:
dh['Matches'] = dh['Matches'].astype('int')

### Calculations

In [79]:
dh['career_length'] = dh['Final_Year'] - dh['Rookie_Year']

In [80]:
dh['career_length'].mean()

np.float64(13.129032258064516)

In [82]:
dh['Batting_Strike_Rate'] = pd.to_numeric(dh['Batting_Strike_Rate'], errors='coerce')

In [83]:
dh[dh['career_length'] > 10]['Batting_Strike_Rate'].mean()

np.float64(50.14780487804878)

In [84]:
dh[dh['Rookie_Year'] < 1960]['Player'].count()

np.int64(23)

In [85]:
dh.groupby('Country')['Highest_Inns_Score'].max().to_frame('Highinncountry').reset_index().sort_values('Highinncountry', ascending = False)

    Country  Highinncountry
6    ICC/WI             400
12       WI             365
2       ENG             336
1       AUS             329
9       PAK             280
10       SA             278
7       IND             248
13      ZIM             232
11       SL             182
0       AFG            <NA>
3   ICC/IND            <NA>
4   ICC/PAK            <NA>
5    ICC/SA            <NA>
8        NZ            <NA>

In [88]:
dh.head()

,Player,Matches,Inns,Not_Outs,Runs,Highest_Inns_Score,Ave,Balls_Faced,Batting_Strike_Rate,100,50,0,4s,6s,Rookie_Year,Final_Year,Country,career_length
0,DG Bradman,52,80,10,6996,<NA>,99.94,9800+,58.60,29,13,7,626+,6,1928,1948,AUS,20
1,PHKD Mendis,14,24,3,1316,182,62.66,2063,63.79,5,5,0,137,24,2022,2025,SL,3
2,AC Voges,20,31,7,1485,269,61.87,2667,55.68,5,4,2,186,5,2015,2016,AUS,1
3,RG Pollock,23,41,4,2256,<NA>,60.97,1707+,54.48,7,11,1,246+,11,1963,1970,SA,7
4,GA Headley,22,40,4,2190,270,60.83,416+,56.00,10,5,2,104+,1,1930,1954,WI,24

In [89]:
dh.groupby('Country')[[100, 50, 0]].mean()

               100         50          0
Country
AFG       2.000000   2.000000   0.000000
AUS      21.600000  29.133333   8.933333
ENG      13.615385  21.846154   4.769231
ICC/IND  29.500000  47.500000  12.000000
ICC/PAK  25.000000  46.000000  15.000000
ICC/SA   36.000000  48.000000  13.500000
ICC/WI   34.000000  48.000000  17.000000
IND      24.000000  32.250000   8.750000
NZ       33.000000  38.000000  11.000000
PAK      21.250000  28.000000   9.500000
SA        9.800000  20.200000   3.400000
SL       22.750000  34.250000   9.250000
WI       16.625000  25.625000   7.250000
ZIM      12.000000  27.000000   5.000000