### Step 1: Import necessary libraries

In [1]:
import pandas as pd

### Step 2: Load the Data

In [2]:
cafe = pd.read_csv(r"C:\Users\Nada\Downloads\cafe_sales.csv")

### Step 3: Explore the Data

##### display the first 10 rows to see the "messy" data

In [3]:
cafe.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
5,TXN_2602893,Smoothie,5,4.0,20.0,Credit Card,NaN,2023-03-31
6,TXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06
7,TXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28
8,TXN_4717867,NaN,5,3.0,15.0,NaN,Takeaway,2023-07-28
9,TXN_2064365,Sandwich,5,4.0,20.0,NaN,In-store,2023-12-31

##### check how many rows and columns

In [4]:
cafe.shape

(10000, 8)

##### display basic info about the dataset to identify nulls and incorrect data types

In [5]:
cafe.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  str
 1   Item              9667 non-null   str
 2   Quantity          9862 non-null   str
 3   Price Per Unit    9821 non-null   str
 4   Total Spent       9827 non-null   str
 5   Payment Method    7421 non-null   str
 6   Location          6735 non-null   str
 7   Transaction Date  9841 non-null   str
dtypes: str(8)
memory usage: 625.1 KB

##### check unique values for `Item`, `Payment Method`, and `Location`

In [6]:
cafe['Item'].unique()

<StringArray>
[  'Coffee',     'Cake',   'Cookie',    'Salad', 'Smoothie',  'UNKNOWN',
 'Sandwich',        nan,    'ERROR',    'Juice',      'Tea']
Length: 11, dtype: str

In [8]:
cafe['Payment Method'].unique()

<StringArray>
['Credit Card', 'Cash', 'UNKNOWN', 'Digital Wallet', 'ERROR', nan]
Length: 6, dtype: str

In [9]:
cafe['Location'].unique()

<StringArray>
['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR']
Length: 5, dtype: str

##### check missing values

In [11]:
cafe.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

### Step 4: Handle Missing Values

##### Spot strings like "UNKNOWN" and "ERROR" that Pandas doesn't see as nulls yet

In [12]:
cafe = cafe.replace(["UNKNOWN", "ERROR", ""], pd.NA)

In [13]:
cafe.isna().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

##### Use `.replace()` to convert "UNKNOWN" and "ERROR" to np.nan

In [14]:
import numpy as np

#cafe = cafe.replace(["UNKNOWN", "ERROR"], np.nan)

In [19]:
cafe.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [21]:
cafe['Total Spent'] = pd.to_numeric(cafe['Total Spent'], errors='coerce')

In [22]:
cafe['Total Spent'] = cafe['Total Spent'].astype(float)

In [41]:
cafe['Total Spent'] = cafe['Total Spent'].fillna(cafe['Quantity']*cafe['Price Per Unit'])

In [24]:
cafe['Price Per Unit'] = pd.to_numeric(cafe['Price Per Unit'], errors='coerce')

In [25]:
cafe['Price Per Unit'] = cafe['Price Per Unit'].astype(float)

In [26]:
cafe['Price Per Unit'] = cafe['Price Per Unit'].fillna(cafe['Price Per Unit'].mean())

In [28]:
cafe['Quantity'] = pd.to_numeric(cafe['Quantity'], errors='coerce')

In [29]:
cafe['Quantity'] = cafe['Quantity'].astype(float)

In [30]:
cafe['Quantity'] = cafe['Quantity'].fillna(cafe['Total Spent']/cafe['Price Per Unit'])

In [33]:
cafe = cafe.dropna(subset=['Payment Method', 'Location', 'Transaction Date', 'Transaction ID', 'Item'])

In [42]:
cafe.head(10)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19
4,TXN_3160411,coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,salad,5.0,5.0,25.000000,Cash,Takeaway,2023-11-07
12,TXN_7619095,sandwich,2.0,4.0,8.000000,Cash,In-store,2023-05-03
15,TXN_2847255,salad,3.0,5.0,15.000000,Credit Card,In-store,2023-11-15
17,TXN_6769710,juice,2.0,3.0,6.000000,Cash,In-store,2023-02-24
19,TXN_3709394,juice,4.0,3.0,12.000000,Cash,Takeaway,2023-01-15
20,TXN_3522028,smoothie,5.0,4.0,20.000000,Cash,In-store,2023-04-04

### Step 5:Text Sanitization

##### remove hidden spaces from all string columns

In [35]:
cafe.dtypes

Transaction ID          str
Item                    str
Quantity            float64
Price Per Unit      float64
Total Spent         float64
Payment Method          str
Location                str
Transaction Date        str
dtype: object

In [36]:
cafe = cafe.apply(lambda x: x.str.strip() if x.dtype == "str" else x)

In [43]:
cafe

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19
4,TXN_3160411,coffee,2.0,2.0,4.000000,Digital Wallet,In-store,2023-06-11
10,TXN_2548360,salad,5.0,5.0,25.000000,Cash,Takeaway,2023-11-07
...,...,...,...,...,...,...,...,...
9979,TXN_9933628,smoothie,5.0,4.0,20.000000,Cash,In-store,2023-07-20
9984,TXN_3142496,smoothie,1.0,4.0,4.000000,Cash,Takeaway,2023-07-27
9986,TXN_2858441,sandwich,2.0,4.0,8.000000,Credit Card,In-store,2023-12-14
9991,TXN_3897619,sandwich,3.0,4.0,12.000000,Cash,Takeaway,2023-02-24
9999,TXN_6170729,sandwich,3.0,4.0,12.000000,Cash,In-store,2023-11-07

##### convert all Item names to lowercase for consistency

In [38]:
cafe['Item'] = cafe['Item'].str.lower()

In [44]:
cafe.head(3)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,coffee,2.0,2.0,4.000000,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,cake,4.0,3.0,12.000000,Cash,In-store,2023-05-16
2,TXN_4271903,cookie,4.0,1.0,8.924352,Credit Card,In-store,2023-07-19

##### use a dictionary to fix any typos in item names if they exist

In [40]:
cafe['Item'].unique()

<StringArray>
['coffee', 'cake', 'cookie', 'salad', 'sandwich', 'juice', 'smoothie', 'tea']
Length: 8, dtype: str

### Step 6: Fix Data Types
##### fix incorrect data types (Quantity, Price Per Unit, Total Spent .....)

In [ ]:
# ✔

##### identify and fix rows where Quantity might be zero or negative

In [ ]:
# ✔

### Step 7: Handle Missing Values (Part 2: Fill NaNs)

##### fill missing `Price Per Unit`

In [ ]:
# ✔

##### handle other missing values appropriately (like Payment Method or Location)

In [ ]:
#✔

In [ ]:
# ✔

### Step 8: Logical Validation

##### create a new column `Expected_Total` by multiplying `Quantity * Price Per Unit`

In [45]:
cafe['Expected_Total'] = cafe['Quantity'] * cafe['Price Per Unit']

##### filter rows where Total Spent is NOT equal to Expected_Total

In [46]:
cafe[cafe['Total Spent'] != cafe['Expected_Total']]

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
2,TXN_4271903,cookie,4.0,1.000000,8.924352,Credit Card,In-store,2023-07-19,4.000000
94,TXN_6289610,juice,3.0,3.000000,8.924352,Cash,Takeaway,2023-08-07,9.000000
146,TXN_7623634,cake,2.0,3.000000,8.924352,Credit Card,In-store,2023-07-11,6.000000
147,TXN_9336980,salad,4.0,2.949984,20.000000,Cash,In-store,2023-06-06,11.799937
161,TXN_7965998,juice,1.0,2.949984,3.000000,Credit Card,In-store,2023-11-02,2.949984
...,...,...,...,...,...,...,...,...,...
9890,TXN_2749289,smoothie,2.0,4.000000,8.924352,Digital Wallet,Takeaway,2023-05-05,8.000000
9893,TXN_3809533,juice,2.0,2.949984,8.924352,Digital Wallet,Takeaway,2023-02-02,5.899968
9926,TXN_2464706,cake,4.0,2.949984,12.000000,Digital Wallet,Takeaway,2023-11-09,11.799937
9954,TXN_1191659,coffee,4.0,2.000000,8.924352,Credit Card,In-store,2023-11-21,8.000000
9977,TXN_5548914,juice,2.0,3.000000,8.924352,Digital Wallet,In-store,2023-11-04,6.000000

##### fill missing or incorrect Total Spent values using the Expected_Total calculation.

In [47]:
cafe['Total Spent'] = cafe['Total Spent'].fillna(cafe['Expected_Total'])

In [48]:
cafe.loc[(cafe['Total Spent'].isna()) | (cafe['Total Spent'] != cafe['Expected_Total']),'Total Spent'] = cafe['Expected_Total']

In [49]:
cafe.head(5)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total
0,TXN_1961373,coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0
4,TXN_3160411,coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0
10,TXN_2548360,salad,5.0,5.0,25.0,Cash,Takeaway,2023-11-07,25.0

### Step 9: Handle Dates

##### convert Transaction Date to datetime

In [50]:
cafe['Transaction Date'] = pd.to_datetime(cafe['Transaction Date'])

##### identify transactions with dates in the future (if any) and handle them

In [51]:
today = pd.Timestamp.today().normalize()

In [52]:
future = cafe[cafe['Transaction Date'] > today]
future

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date, Expected_Total]
Index: []

##### extract "Year" and "Month" into separate columns for analysis

In [53]:
cafe['Year'] = cafe['Transaction Date'].dt.year

In [54]:
cafe['Month'] = cafe['Transaction Date'].dt.month

In [55]:
cafe.head(4)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total,Year,Month
0,TXN_1961373,coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0,2023,9
1,TXN_4977031,cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0,2023,5
2,TXN_4271903,cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19,4.0,2023,7
4,TXN_3160411,coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0,2023,6

### Step 10: Remove Duplicates

##### check for duplicates

In [56]:
cafe.duplicated()

0       False
1       False
2       False
4       False
10      False
        ...
9979    False
9984    False
9986    False
9991    False
9999    False
Length: 3580, dtype: bool

##### drop duplicates if found

### Step 9: Clean Text Data

#####  clean text columns (strip spaces, unify format)

In [57]:
cafe.dtypes

Transaction ID                 str
Item                           str
Quantity                   float64
Price Per Unit             float64
Total Spent                float64
Payment Method                 str
Location                       str
Transaction Date    datetime64[us]
Expected_Total             float64
Year                         int32
Month                        int32
dtype: object

In [58]:
cafe = cafe.apply(lambda x: x.str.strip().str.lower() if x.dtype == "str" else x)

In [59]:
cafe.head(6)

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Expected_Total,Year,Month
0,txn_1961373,coffee,2.0,2.0,4.0,credit card,takeaway,2023-09-08,4.0,2023,9
1,txn_4977031,cake,4.0,3.0,12.0,cash,in-store,2023-05-16,12.0,2023,5
2,txn_4271903,cookie,4.0,1.0,4.0,credit card,in-store,2023-07-19,4.0,2023,7
4,txn_3160411,coffee,2.0,2.0,4.0,digital wallet,in-store,2023-06-11,4.0,2023,6
10,txn_2548360,salad,5.0,5.0,25.0,cash,takeaway,2023-11-07,25.0,2023,11
12,txn_7619095,sandwich,2.0,4.0,8.0,cash,in-store,2023-05-03,8.0,2023,5